Pandas is one of the most popular Python libraries for Data Science and Analytics.

Because pandas helps you to manage two-dimensional data tables in Python. Of course, it has many more features.

In [2]:
import numpy as np
import pandas as pd

## Pandas data structures

There are two types of data structures in pandas: Series and DataFrames.

### Series

A pandas Series is a one dimensional data structure (“a one dimensional ndarray”) that can store values — and for every value it holds a unique index, too.

### DataFrame

a pandas DataFrame is a two (or more) dimensional data structure – basically a table with rows and columns. The columns have names and the rows have indexes.

## Loading a .csv file into a pandas DataFrame

There is a function for it, called read_csv().

## Selecting data from a dataframe in pandas

### Print the whole dataframe

In [10]:
data = pd.read_csv('data.csv', skiprows=4)
data

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver
5,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,1200m freestyle,M,Bronze
6,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,1200m freestyle,M,Gold
7,Athens,1896,Aquatics,Swimming,"ANDREOU, Joannis",GRE,Men,1200m freestyle,M,Silver
8,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,400m freestyle,M,Bronze
9,Athens,1896,Aquatics,Swimming,"NEUMANN, Paul",AUT,Men,400m freestyle,M,Gold
10,Athens,1896,Aquatics,Swimming,"PEPANOS, Antonios",GRE,Men,400m freestyle,M,Silver
11,Athens,1896,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
12,Athens,1896,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
13,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
14,Athens,1896,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver
15,Athens,1896,Athletics,Athletics,"CURTIS, Thomas",USA,Men,110m hurdles,M,Gold
16,Athens,1896,Athletics,Athletics,"GOULDING, Grantley",GBR,Men,110m hurdles,M,Silver
17,Athens,1896,Athletics,Athletics,"LERMUSIAUX, Albin",FRA,Men,1500m,M,Bronze
18,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,1500m,M,Gold
19,Athens,1896,Athletics,Athletics,"BLAKE, Arthur",USA,Men,1500m,M,Silver
20,Athens,1896,Athletics,Athletics,"GMELIN, Charles",GBR,Men,400m,M,Bronze
21,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,400m,M,Gold
22,Athens,1896,Athletics,Athletics,"JAMISON, Herbert",USA,Men,400m,M,Silver
23,Athens,1896,Athletics,Athletics,"GOLEMIS, Dimitrios",GRE,Men,800m,M,Bronze
24,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,800m,M,Gold
25,Athens,1896,Athletics,Athletics,"DANI, Nandor",HUN,Men,800m,M,Silver
26,Athens,1896,Athletics,Athletics,"VERSIS, Sotirios",GRE,Men,discus throw,M,Bronze
27,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,discus throw,M,Gold
28,Athens,1896,Athletics,Athletics,"PARASKEVOPOULOS, Panagiotis",GRE,Men,discus throw,M,Silver
29,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,high jump,M,Gold
...,...,...,...,...,...,...,...,...,...,...
29186,Beijing,2008,Wrestling,Wrestling Free.,"MUTALIMOV, Marid",KAZ,Men,96 - 120kg,M,Bronze
29187,Beijing,2008,Wrestling,Wrestling Free.,"TAYMAZOV, Artur",UZB,Men,96 - 120kg,M,Gold
29188,Beijing,2008,Wrestling,Wrestling Free.,"AKHMEDOV, Bakhtiyar",RUS,Men,96 - 120kg,M,Silver
29189,Beijing,2008,Wrestling,Wrestling Gre-R,"AMOYAN, Roman",ARM,Men,- 55kg,M,Bronze
29190,Beijing,2008,Wrestling,Wrestling Gre-R,"PARK, Eun-Chul",KOR,Men,- 55kg,M,Bronze
29191,Beijing,2008,Wrestling,Wrestling Gre-R,"MANKIEV, Nazyr",RUS,Men,- 55kg,M,Gold
29192,Beijing,2008,Wrestling,Wrestling Gre-R,"BAYRAMOV, Rovshan",AZE,Men,- 55kg,M,Silver
29193,Beijing,2008,Wrestling,Wrestling Gre-R,"TENGIZBAYEV, Nurbakyt",KAZ,Men,55 - 60kg,M,Bronze
29194,Beijing,2008,Wrestling,Wrestling Gre-R,"TIUMENBAEV, Ruslan",KGZ,Men,55 - 60kg,M,Bronze
29195,Beijing,2008,Wrestling,Wrestling Gre-R,"ALBIEV, Islam-Beka",RUS,Men,55 - 60kg,M,Gold
29196,Beijing,2008,Wrestling,Wrestling Gre-R,"RAHIMOV, Vitaliy",AZE,Men,55 - 60kg,M,Silver
29197,Beijing,2008,Wrestling,Wrestling Gre-R,"SIAMIONAU, Mikhail",BLR,Men,60 - 66kg,M,Bronze
29198,Beijing,2008,Wrestling,Wrestling Gre-R,"VARDANYAN, Armen",UKR,Men,60 - 66kg,M,Bronze
29199,Beijing,2008,Wrestling,Wrestling Gre-R,"GUENOT, Steeve",FRA,Men,60 - 66kg,M,Gold
29200,Beijing,2008,Wrestling,Wrestling Gre-R,"BEGALIEV, Kanatbek",KGZ,Men,60 - 66kg,M,Silver
29201,Beijing,2008,Wrestling,Wrestling Gre-R,"GUENOT, Christophe",FRA,Men,66 - 74kg,M,Bronze
29202,Beijing,2008,Wrestling,Wrestling Gre-R,"YANAKIEV, Yavor",BUL,Men,66 - 74kg,M,Bronze
29203,Beijing,2008,Wrestling,Wrestling Gre-R,"KVIRKELIA, Manuchar",GEO,Men,66 - 74kg,M,Gold
29204,Beijing,2008,Wrestling,Wrestling Gre-R,"CHANG, Yongxiang",CHN,Men,66 - 74kg,M,Silver
29205,Beijing,2008,Wrestling,Wrestling Gre-R,"AVLUCA, Nazmi",TUR,Men,74 - 84kg,M,Bronze
29206,Beijing,2008,Wrestling,Wrestling Gre-R,"MINGUZZI, Andrea",ITA,Men,74 - 84kg,M,Gold
29207,Beijing,2008,Wrestling,Wrestling Gre-R,"FODOR, Zoltan",HUN,Men,74 - 84kg,M,Silver
29208,Beijing,2008,Wrestling,Wrestling Gre-R,"MAMBETOV, Asset",KAZ,Men,84 - 96kg,M,Bronze
29209,Beijing,2008,Wrestling,Wrestling Gre-R,"WHEELER, Adam",USA,Men,84 - 96kg,M,Bronze
29210,Beijing,2008,Wrestling,Wrestling Gre-R,"KHUSHTOV, Aslanbek",RUS,Men,84 - 96kg,M,Gold
29211,Beijing,2008,Wrestling,Wrestling Gre-R,"ENGLICH, Mirko",GER,Men,84 - 96kg,M,Silver
29212,Beijing,2008,Wrestling,Wrestling Gre-R,"MIZGAITIS, Mindaugas",LTU,Men,96 - 120kg,M,Bronze
29213,Beijing,2008,Wrestling,Wrestling Gre-R,"PATRIKEEV, Yuri",ARM,Men,96 - 120kg,M,Bronze
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold
29215,Beijing,2008,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",RUS,Men,96 - 120kg,M,Silver

### Print a sample of your dataframe

Sometimes, it’s handy not to print the whole dataframe and flood your screen with data. When a few lines is enough, you can print only the first 5 lines – by typing:

In [12]:
data.head()

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

Or the last few lines by typing:

In [14]:
data.tail()

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
29211,Beijing,2008,Wrestling,Wrestling Gre-R,"ENGLICH, Mirko",GER,Men,84 - 96kg,M,Silver
29212,Beijing,2008,Wrestling,Wrestling Gre-R,"MIZGAITIS, Mindaugas",LTU,Men,96 - 120kg,M,Bronze
29213,Beijing,2008,Wrestling,Wrestling Gre-R,"PATRIKEEV, Yuri",ARM,Men,96 - 120kg,M,Bronze
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold
29215,Beijing,2008,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",RUS,Men,96 - 120kg,M,Silver

Or a few random lines by typing:

In [15]:
data.sample(10)

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
19362,Seoul,1988,Shooting,Shooting,"SPERBER, Silvia",FRG,Women,10m air rifle (40 shots),W,Silver
20863,Barcelona,1992,Rowing,Rowing,"ETTINGSHAUSEN, Colin",GER,Men,coxless pair (2-),M,Silver
20632,Barcelona,1992,Handball,Handball,"HAJAS, Erik",SWE,Men,handball,M,Silver
12128,Mexico,1968,Cycling,Cycling Road,"FÄGLUM-PETTERSSON, Tomas",SWE,Men,team time trial,M,Silver
24565,Sydney,2000,Hockey,Hockey,"FERRARI, Maria Paz",ARG,Women,hockey,W,Silver
752,St Louis,1904,Athletics,Athletics,"LIGHTBODY, James",USA,Men,3000m steeplechase,M,Gold
14469,Montreal,1976,Fencing,Fencing,"POFFET, Michel",SUI,Men,épée team,M,Bronze
12172,Mexico,1968,Equestrian,Eventing,"COBCROFT, Brian W.B.",AUS,Men,team,X,Bronze
17182,Los Angeles,1984,Equestrian,Dressage,H:: LIMANDUS,SUI,Men,individual,X,Bronze
23400,Sydney,2000,Aquatics,Synchronized S.,"PERCHINA, Irina",RUS,Women,team,W,Gold

### Select specific columns of your dataframe

This one is a bit tricky! Let’s say you want to print the ‘City’ and the ‘Medal’ columns only.
You should use this syntax:

In [17]:
data[['City','Medal']]

          City   Medal
0       Athens    Gold
1       Athens  Silver
2       Athens  Bronze
3       Athens    Gold
4       Athens  Silver
5       Athens  Bronze
6       Athens    Gold
7       Athens  Silver
8       Athens  Bronze
9       Athens    Gold
10      Athens  Silver
11      Athens  Bronze
12      Athens  Bronze
13      Athens    Gold
14      Athens  Silver
15      Athens    Gold
16      Athens  Silver
17      Athens  Bronze
18      Athens    Gold
19      Athens  Silver
20      Athens  Bronze
21      Athens    Gold
22      Athens  Silver
23      Athens  Bronze
24      Athens    Gold
25      Athens  Silver
26      Athens  Bronze
27      Athens    Gold
28      Athens  Silver
29      Athens    Gold
...        ...     ...
29186  Beijing  Bronze
29187  Beijing    Gold
29188  Beijing  Silver
29189  Beijing  Bronze
29190  Beijing  Bronze
29191  Beijing    Gold
29192  Beijing  Silver
29193  Beijing  Bronze
29194  Beijing  Bronze
29195  Beijing    Gold
29196  Beijing  Silver
29197  Beijing  Bronze
29198  Beijing  Bronze
29199  Beijing    Gold
29200  Beijing  Silver
29201  Beijing  Bronze
29202  Beijing  Bronze
29203  Beijing    Gold
29204  Beijing  Silver
29205  Beijing  Bronze
29206  Beijing    Gold
29207  Beijing  Silver
29208  Beijing  Bronze
29209  Beijing  Bronze
29210  Beijing    Gold
29211  Beijing  Silver
29212  Beijing  Bronze
29213  Beijing  Bronze
29214  Beijing    Gold
29215  Beijing  Silver

[29216 rows x 2 columns]

the outer bracket frames tell pandas that you want to select columns, and the inner brackets are for the list (remember? Python lists go between bracket frames) of the column names.

By the way, if you change the order of the column names, the order of the returned columns will change, too:

In [18]:
data[['Medal','City']]

        Medal     City
0        Gold   Athens
1      Silver   Athens
2      Bronze   Athens
3        Gold   Athens
4      Silver   Athens
5      Bronze   Athens
6        Gold   Athens
7      Silver   Athens
8      Bronze   Athens
9        Gold   Athens
10     Silver   Athens
11     Bronze   Athens
12     Bronze   Athens
13       Gold   Athens
14     Silver   Athens
15       Gold   Athens
16     Silver   Athens
17     Bronze   Athens
18       Gold   Athens
19     Silver   Athens
20     Bronze   Athens
21       Gold   Athens
22     Silver   Athens
23     Bronze   Athens
24       Gold   Athens
25     Silver   Athens
26     Bronze   Athens
27       Gold   Athens
28     Silver   Athens
29       Gold   Athens
...       ...      ...
29186  Bronze  Beijing
29187    Gold  Beijing
29188  Silver  Beijing
29189  Bronze  Beijing
29190  Bronze  Beijing
29191    Gold  Beijing
29192  Silver  Beijing
29193  Bronze  Beijing
29194  Bronze  Beijing
29195    Gold  Beijing
29196  Silver  Beijing
29197  Bronze  Beijing
29198  Bronze  Beijing
29199    Gold  Beijing
29200  Silver  Beijing
29201  Bronze  Beijing
29202  Bronze  Beijing
29203    Gold  Beijing
29204  Silver  Beijing
29205  Bronze  Beijing
29206    Gold  Beijing
29207  Silver  Beijing
29208  Bronze  Beijing
29209  Bronze  Beijing
29210    Gold  Beijing
29211  Silver  Beijing
29212  Bronze  Beijing
29213  Bronze  Beijing
29214    Gold  Beijing
29215  Silver  Beijing

[29216 rows x 2 columns]

This is the DataFrame of your selected columns.

In [19]:
data.City

0         Athens
1         Athens
2         Athens
3         Athens
4         Athens
5         Athens
6         Athens
7         Athens
8         Athens
9         Athens
10        Athens
11        Athens
12        Athens
13        Athens
14        Athens
15        Athens
16        Athens
17        Athens
18        Athens
19        Athens
20        Athens
21        Athens
22        Athens
23        Athens
24        Athens
25        Athens
26        Athens
27        Athens
28        Athens
29        Athens
          ...
29186    Beijing
29187    Beijing
29188    Beijing
29189    Beijing
29190    Beijing
29191    Beijing
29192    Beijing
29193    Beijing
29194    Beijing
29195    Beijing
29196    Beijing
29197    Beijing
29198    Beijing
29199    Beijing
29200    Beijing
29201    Beijing
29202    Beijing
29203    Beijing
29204    Beijing
29205    Beijing
29206    Beijing
29207    Beijing
29208    Beijing
29209    Beijing
29210    Beijing
29211    Beijing
29212    Beijing
29213    Beijing
29214    Beijing
29215    Beijing
Name: City, Length: 29216, dtype: object

Sometimes (especially in predictive analytics projects), you want to get Series objects instead of DataFrames.

### Filter for specific values in your dataframe

Let’s say, you want to see a list of only the users who earned from the ‘Gold’ source. In this case you have to filter for the ‘Gold’ value in the ‘Medal’ column:

In [20]:
data[data.Medal == 'Gold']

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
6,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,1200m freestyle,M,Gold
9,Athens,1896,Aquatics,Swimming,"NEUMANN, Paul",AUT,Men,400m freestyle,M,Gold
13,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
15,Athens,1896,Athletics,Athletics,"CURTIS, Thomas",USA,Men,110m hurdles,M,Gold
18,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,1500m,M,Gold
21,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,400m,M,Gold
24,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,800m,M,Gold
27,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,discus throw,M,Gold
29,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,high jump,M,Gold
33,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,long jump,M,Gold
36,Athens,1896,Athletics,Athletics,"LOUIS, Spyridon",GRE,Men,marathon,M,Gold
40,Athens,1896,Athletics,Athletics,"HOYT, William Welles",USA,Men,pole vault,M,Gold
43,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,shot put,M,Gold
46,Athens,1896,Athletics,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold
49,Athens,1896,Cycling,Cycling Road,"KONSTANTINIDIS, Aristidis",GRE,Men,individual road race,M,Gold
51,Athens,1896,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
54,Athens,1896,Cycling,Cycling Track,"MASSON, Paul",FRA,Men,10km,M,Gold
56,Athens,1896,Cycling,Cycling Track,"SCHMAL, Adolf",AUT,Men,12-hour race,M,Gold
59,Athens,1896,Cycling,Cycling Track,"MASSON, Paul",FRA,Men,1km time trial,M,Gold
62,Athens,1896,Cycling,Cycling Track,"MASSON, Paul",FRA,Men,Sprint indivual,M,Gold
65,Athens,1896,Fencing,Fencing,"GRAVELOTTE, Eugène-Henri",FRA,Men,foil individual,M,Gold
67,Athens,1896,Fencing,Fencing,"PYRGOS, Leonidas",GRE,Men,"foil, masters",M,Gold
70,Athens,1896,Fencing,Fencing,"GEORGIADIS, Ioannis",GRE,Men,sabre individual,M,Gold
72,Athens,1896,Gymnastics,Artistic G.,"WEINGÄRTNER, Hermann",GER,Men,horizontal bar,M,Gold
74,Athens,1896,Gymnastics,Artistic G.,"FLATOW, Alfred",GER,Men,parallel bars,M,Gold
76,Athens,1896,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,pommel horse,M,Gold
79,Athens,1896,Gymnastics,Artistic G.,"MITROPOULOS, Ioannis",GRE,Men,rings,M,Gold
82,Athens,1896,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,rope climbing,M,Gold
...,...,...,...,...,...,...,...,...,...,...
29110,Beijing,2008,Weightlifting,Weightlifting,"ARAMNAU, Andrei",BLR,Men,105kg,M,Gold
29113,Beijing,2008,Weightlifting,Weightlifting,"CHEN, Xiexia",CHN,Women,48kg,W,Gold
29116,Beijing,2008,Weightlifting,Weightlifting,"JAROENRATTANATARAKOON, Prapawadee",THA,Women,53kg,W,Gold
29119,Beijing,2008,Weightlifting,Weightlifting,"CHEN, Yanqing",CHN,Women,58kg,W,Gold
29122,Beijing,2008,Weightlifting,Weightlifting,"ZHANG, Xiangxiang",CHN,Men,62kg,M,Gold
29125,Beijing,2008,Weightlifting,Weightlifting,"PAK, Hyon Suk",PRK,Women,63kg,W,Gold
29128,Beijing,2008,Weightlifting,Weightlifting,"LIAO, Hui",CHN,Men,69kg,M,Gold
29131,Beijing,2008,Weightlifting,Weightlifting,"LIU, Chunhong",CHN,Women,69kg,W,Gold
29134,Beijing,2008,Weightlifting,Weightlifting,"CAO, Lei",CHN,Women,75kg,W,Gold
29137,Beijing,2008,Weightlifting,Weightlifting,"SA, Jaehyouk",KOR,Men,77kg,M,Gold
29140,Beijing,2008,Weightlifting,Weightlifting,"LU, Yong",CHN,Men,85kg,M,Gold
29143,Beijing,2008,Weightlifting,Weightlifting,"ILIN, Ilya",KAZ,Men,94kg,M,Gold
29147,Beijing,2008,Wrestling,Wrestling Free.,"HUYNH, Carol",CAN,Women,- 48kg,W,Gold
29151,Beijing,2008,Wrestling,Wrestling Free.,"CEJUDO, Henry",USA,Men,- 55kg,M,Gold
29155,Beijing,2008,Wrestling,Wrestling Free.,"YOSHIDA, Saori",JPN,Women,48 - 55kg,W,Gold
29159,Beijing,2008,Wrestling,Wrestling Free.,"BATIROV, Mavlet",RUS,Men,55 - 60kg,M,Gold
29163,Beijing,2008,Wrestling,Wrestling Free.,"ICHO, Kaori",JPN,Women,55 - 63kg,W,Gold
29167,Beijing,2008,Wrestling,Wrestling Free.,"SAHIN, Ramazan",TUR,Men,60 - 66kg,M,Gold
29171,Beijing,2008,Wrestling,Wrestling Free.,"WANG, Jiao",CHN,Women,63 - 72kg,W,Gold
29175,Beijing,2008,Wrestling,Wrestling Free.,"SAYTIEV, Buvaysa",RUS,Men,66 - 74kg,M,Gold
29179,Beijing,2008,Wrestling,Wrestling Free.,"MINDORASHVILI, Revazi",GEO,Men,74 - 84kg,M,Gold
29183,Beijing,2008,Wrestling,Wrestling Free.,"MURADOV, Shirvani",RUS,Men,84 - 96kg,M,Gold
29187,Beijing,2008,Wrestling,Wrestling Free.,"TAYMAZOV, Artur",UZB,Men,96 - 120kg,M,Gold
29191,Beijing,2008,Wrestling,Wrestling Gre-R,"MANKIEV, Nazyr",RUS,Men,- 55kg,M,Gold
29195,Beijing,2008,Wrestling,Wrestling Gre-R,"ALBIEV, Islam-Beka",RUS,Men,55 - 60kg,M,Gold
29199,Beijing,2008,Wrestling,Wrestling Gre-R,"GUENOT, Steeve",FRA,Men,60 - 66kg,M,Gold
29203,Beijing,2008,Wrestling,Wrestling Gre-R,"KVIRKELIA, Manuchar",GEO,Men,66 - 74kg,M,Gold
29206,Beijing,2008,Wrestling,Wrestling Gre-R,"MINGUZZI, Andrea",ITA,Men,74 - 84kg,M,Gold
29210,Beijing,2008,Wrestling,Wrestling Gre-R,"KHUSHTOV, Aslanbek",RUS,Men,84 - 96kg,M,Gold
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold

In [7]:
data = pd.read_csv('data.csv', skiprows=4)
data

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver
5,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,1200m freestyle,M,Bronze
6,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,1200m freestyle,M,Gold
7,Athens,1896,Aquatics,Swimming,"ANDREOU, Joannis",GRE,Men,1200m freestyle,M,Silver
8,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,400m freestyle,M,Bronze
9,Athens,1896,Aquatics,Swimming,"NEUMANN, Paul",AUT,Men,400m freestyle,M,Gold
10,Athens,1896,Aquatics,Swimming,"PEPANOS, Antonios",GRE,Men,400m freestyle,M,Silver
11,Athens,1896,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
12,Athens,1896,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
13,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
14,Athens,1896,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver
15,Athens,1896,Athletics,Athletics,"CURTIS, Thomas",USA,Men,110m hurdles,M,Gold
16,Athens,1896,Athletics,Athletics,"GOULDING, Grantley",GBR,Men,110m hurdles,M,Silver
17,Athens,1896,Athletics,Athletics,"LERMUSIAUX, Albin",FRA,Men,1500m,M,Bronze
18,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,1500m,M,Gold
19,Athens,1896,Athletics,Athletics,"BLAKE, Arthur",USA,Men,1500m,M,Silver
20,Athens,1896,Athletics,Athletics,"GMELIN, Charles",GBR,Men,400m,M,Bronze
21,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,400m,M,Gold
22,Athens,1896,Athletics,Athletics,"JAMISON, Herbert",USA,Men,400m,M,Silver
23,Athens,1896,Athletics,Athletics,"GOLEMIS, Dimitrios",GRE,Men,800m,M,Bronze
24,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,800m,M,Gold
25,Athens,1896,Athletics,Athletics,"DANI, Nandor",HUN,Men,800m,M,Silver
26,Athens,1896,Athletics,Athletics,"VERSIS, Sotirios",GRE,Men,discus throw,M,Bronze
27,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,discus throw,M,Gold
28,Athens,1896,Athletics,Athletics,"PARASKEVOPOULOS, Panagiotis",GRE,Men,discus throw,M,Silver
29,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,high jump,M,Gold
...,...,...,...,...,...,...,...,...,...,...
29186,Beijing,2008,Wrestling,Wrestling Free.,"MUTALIMOV, Marid",KAZ,Men,96 - 120kg,M,Bronze
29187,Beijing,2008,Wrestling,Wrestling Free.,"TAYMAZOV, Artur",UZB,Men,96 - 120kg,M,Gold
29188,Beijing,2008,Wrestling,Wrestling Free.,"AKHMEDOV, Bakhtiyar",RUS,Men,96 - 120kg,M,Silver
29189,Beijing,2008,Wrestling,Wrestling Gre-R,"AMOYAN, Roman",ARM,Men,- 55kg,M,Bronze
29190,Beijing,2008,Wrestling,Wrestling Gre-R,"PARK, Eun-Chul",KOR,Men,- 55kg,M,Bronze
29191,Beijing,2008,Wrestling,Wrestling Gre-R,"MANKIEV, Nazyr",RUS,Men,- 55kg,M,Gold
29192,Beijing,2008,Wrestling,Wrestling Gre-R,"BAYRAMOV, Rovshan",AZE,Men,- 55kg,M,Silver
29193,Beijing,2008,Wrestling,Wrestling Gre-R,"TENGIZBAYEV, Nurbakyt",KAZ,Men,55 - 60kg,M,Bronze
29194,Beijing,2008,Wrestling,Wrestling Gre-R,"TIUMENBAEV, Ruslan",KGZ,Men,55 - 60kg,M,Bronze
29195,Beijing,2008,Wrestling,Wrestling Gre-R,"ALBIEV, Islam-Beka",RUS,Men,55 - 60kg,M,Gold
29196,Beijing,2008,Wrestling,Wrestling Gre-R,"RAHIMOV, Vitaliy",AZE,Men,55 - 60kg,M,Silver
29197,Beijing,2008,Wrestling,Wrestling Gre-R,"SIAMIONAU, Mikhail",BLR,Men,60 - 66kg,M,Bronze
29198,Beijing,2008,Wrestling,Wrestling Gre-R,"VARDANYAN, Armen",UKR,Men,60 - 66kg,M,Bronze
29199,Beijing,2008,Wrestling,Wrestling Gre-R,"GUENOT, Steeve",FRA,Men,60 - 66kg,M,Gold
29200,Beijing,2008,Wrestling,Wrestling Gre-R,"BEGALIEV, Kanatbek",KGZ,Men,60 - 66kg,M,Silver
29201,Beijing,2008,Wrestling,Wrestling Gre-R,"GUENOT, Christophe",FRA,Men,66 - 74kg,M,Bronze
29202,Beijing,2008,Wrestling,Wrestling Gre-R,"YANAKIEV, Yavor",BUL,Men,66 - 74kg,M,Bronze
29203,Beijing,2008,Wrestling,Wrestling Gre-R,"KVIRKELIA, Manuchar",GEO,Men,66 - 74kg,M,Gold
29204,Beijing,2008,Wrestling,Wrestling Gre-R,"CHANG, Yongxiang",CHN,Men,66 - 74kg,M,Silver
29205,Beijing,2008,Wrestling,Wrestling Gre-R,"AVLUCA, Nazmi",TUR,Men,74 - 84kg,M,Bronze
29206,Beijing,2008,Wrestling,Wrestling Gre-R,"MINGUZZI, Andrea",ITA,Men,74 - 84kg,M,Gold
29207,Beijing,2008,Wrestling,Wrestling Gre-R,"FODOR, Zoltan",HUN,Men,74 - 84kg,M,Silver
29208,Beijing,2008,Wrestling,Wrestling Gre-R,"MAMBETOV, Asset",KAZ,Men,84 - 96kg,M,Bronze
29209,Beijing,2008,Wrestling,Wrestling Gre-R,"WHEELER, Adam",USA,Men,84 - 96kg,M,Bronze
29210,Beijing,2008,Wrestling,Wrestling Gre-R,"KHUSHTOV, Aslanbek",RUS,Men,84 - 96kg,M,Gold
29211,Beijing,2008,Wrestling,Wrestling Gre-R,"ENGLICH, Mirko",GER,Men,84 - 96kg,M,Silver
29212,Beijing,2008,Wrestling,Wrestling Gre-R,"MIZGAITIS, Mindaugas",LTU,Men,96 - 120kg,M,Bronze
29213,Beijing,2008,Wrestling,Wrestling Gre-R,"PATRIKEEV, Yuri",ARM,Men,96 - 120kg,M,Bronze
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold
29215,Beijing,2008,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",RUS,Men,96 - 120kg,M,Silver

### Basic Analysis of Dataset

pandas has several methods that allow you to quickly analyze a dataset and get an idea of the type and amount of data you are dealing with along with some important statistics. 

- .shape - returns the row and column count of a dataset
- .describe() - returns statistics about the numerical columns in a dataset 
- .dtypes returns the data type of each column

In [22]:
data.shape

(29216, 10)

In [24]:
data.describe()

            Edition
count  29216.000000
mean    1967.713171
std       32.406293
min     1896.000000
25%     1948.000000
50%     1976.000000
75%     1996.000000
max     2008.000000

Here are some additional methods that can give you statistics of a DataFrame or particular column in a DataFrame.
- .mean(axis=0 [will give you the calculated value per column]) - returns the statistical mean 
- .median(axis=0 [will give you the calculated value per column]) - returns the statistical median 
- .mode(axis=0 [will give you the calculated value per column]) - returns the statistical mode
- .count() - gives number of total values in column
- .unique() - returns array of all unique values in that column
- .value_counts() - returns object containing counts of unique values

In [28]:
data[data.Medal == 'Gold'].mean()

Edition    1966.510457
dtype: float64

In [29]:
data[data.Medal == 'Gold'].median()

Edition    1976.0
dtype: float64

In [32]:
data[data.Medal == 'Gold'].mode()

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,2008,Aquatics,Athletics,"PHELPS, Michael",USA,Men,football,M,Gold

In [34]:
data[data.Medal == 'Gold'].count()

City            9850
Edition         9850
Sport           9850
Discipline      9850
Athlete         9850
NOC             9850
Gender          9850
Event           9850
Event_gender    9850
Medal           9850
dtype: int64

In [39]:
data[data.Medal == 'Gold'].count().unique()

array([9850], dtype=int64)

In [41]:
data[data.Medal == 'Gold'].count().value_counts()

9850    10
dtype: int64